In [1]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [4]:
a.dtype

dtype('int32')

In [5]:
a.ndim

2

In [9]:
b=np.array([2.,3,4])
b

array([2., 3., 4.])

In [10]:
b.dtype

dtype('float64')

In [14]:
c=np.array([(1.5,2,3), (4,5,6)])
c

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [15]:
c.dtype

dtype('float64')

In [16]:
c=np.array([(1.5,2,3), (4,5,6)],dtype=complex )
c

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

In [18]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
b=np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a=np.linspace(1,10,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
pi=3.14
x = np.linspace( 0, 2*pi, 50 )
x

array([0.        , 0.12816327, 0.25632653, 0.3844898 , 0.51265306,
       0.64081633, 0.76897959, 0.89714286, 1.02530612, 1.15346939,
       1.28163265, 1.40979592, 1.53795918, 1.66612245, 1.79428571,
       1.92244898, 2.05061224, 2.17877551, 2.30693878, 2.43510204,
       2.56326531, 2.69142857, 2.81959184, 2.9477551 , 3.07591837,
       3.20408163, 3.3322449 , 3.46040816, 3.58857143, 3.71673469,
       3.84489796, 3.97306122, 4.10122449, 4.22938776, 4.35755102,
       4.48571429, 4.61387755, 4.74204082, 4.87020408, 4.99836735,
       5.12653061, 5.25469388, 5.38285714, 5.51102041, 5.63918367,
       5.76734694, 5.8955102 , 6.02367347, 6.15183673, 6.28      ])

In [33]:
f = np.sin(x)
f

array([ 0.        ,  0.12781269,  0.25352882,  0.37508623,  0.49049097,
        0.59785001,  0.69540231,  0.78154769,  0.85487306,  0.91417565,
        0.95848269,  0.98706741,  0.99946091,  0.9954599 ,  0.97513002,
        0.93880474,  0.88707991,  0.820804  ,  0.74106416,  0.64916838,
        0.54662406,  0.43511328,  0.31646518,  0.19262599,  0.06562709,
       -0.06244832, -0.18949936, -0.31344198, -0.4322431 , -0.54395398,
       -0.6467422 , -0.73892168, -0.81898036, -0.88560503, -0.9377028 ,
       -0.97441911, -0.99515167, -0.99956042, -0.98757302, -0.95938612,
       -0.91546207, -0.85652137, -0.78353086, -0.69768781, -0.60040034,
       -0.4932643 , -0.37803707, -0.25660877, -0.13097122, -0.0031853 ])

In [34]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [37]:
a=np.arange(1,40)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [47]:
arr=np.array([3,5,1,12,8,9,22,46,51,42,16,92,7,],dtype=int)
np.sort(arr)

array([ 1,  3,  5,  7,  8,  9, 12, 16, 22, 42, 46, 51, 92])

In [64]:
a=np.array([[1,2] , [3,4]])
b=np.array([[6,7]])
x=np.concatenate((a,b),axis=0)
x

array([[1, 2],
       [3, 4],
       [6, 7]])

In [65]:
x.ndim

2

In [66]:
x.size

6

In [67]:
x.shape

(3, 2)

In [68]:
x.reshape(2,3)

array([[1, 2, 3],
       [4, 6, 7]])

In [69]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [70]:
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [71]:
x.shape

(3, 2)

In [72]:
y=x[np.newaxis,:]
y.shape

(1, 3, 2)

In [77]:
data=np.arange(10)
data[1]

1

In [81]:
data[0:4]

array([0, 1, 2, 3])

In [82]:
data[5::]

array([5, 6, 7, 8, 9])

In [83]:
data[5:]

array([5, 6, 7, 8, 9])

In [84]:
data[-2:]

array([8, 9])

In [86]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[a<5])

[1 2 3 4]


In [87]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [88]:
print(a[a%2==0])

[ 2  4  6  8 10 12]


In [89]:
print(a[(a>2)&(a<11)])

[ 3  4  5  6  7  8  9 10]


In [93]:
print(a[(a>7)| (a==3)] )

[ 3  8  9 10 11 12]


In [94]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
a1=a[3:8]

In [96]:
a1

array([3, 4, 5, 6, 7])

In [97]:
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [102]:
np.hsplit(x,6)

[array([[ 1,  2],
        [13, 14]]), array([[ 3,  4],
        [15, 16]]), array([[ 5,  6],
        [17, 18]]), array([[ 7,  8],
        [19, 20]]), array([[ 9, 10],
        [21, 22]]), array([[11, 12],
        [23, 24]])]

In [105]:
a=np.array([1,2])
b=np.ones(2,dtype=int)
b

array([1, 1])

In [106]:
a+b

array([2, 3])

In [107]:
a=np.array([2,3,5,6,7,8])
a.sum()

31

In [112]:
b=np.array([[1,2],[3,4]])
b.sum(axis=0)

array([4, 6])

In [113]:
b.sum(axis=1)

array([3, 7])

In [125]:
a=np.ones([2,4,4],dtype=int)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [130]:
a=np.array([1,2,2,3,2,3,4,5,5,6,6,6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [131]:
b=np.array([1,2,2,3,2,3,4,5,5,6,6,6])
np.unique(b,return_index=True)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 3, 6, 7, 9], dtype=int64))

In [132]:
c=np.array([1,2,2,3,2,3,4,5,5,6,6,6])
np.unique(c,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([1, 3, 2, 1, 2, 3], dtype=int64))

In [133]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [139]:
a1=a.reshape(2,3)
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [140]:
a1.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [141]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.flip(b)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [143]:
a2 = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])

In [144]:
np.flip(a2)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [145]:
np.flip(a2,axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [146]:
np.flip(a2,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [147]:
np.flip(a2[1])

array([8, 7, 6, 5])